# Generated by Django 3.2.16 on 2023-01-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_auto_20221214_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_date', models.DateTimeField()),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher')),
            ],
        ),
    ]
