# Generated by Django 3.2.16 on 2023-01-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_referrals'),
        ('voucher', '0012_referalvoucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('referral', 'Referral'), ('promotional', 'Promotional'), ('secondorder', 'Secondorder')], default='referral', max_length=255)),
                ('currently_used', models.BooleanField(default=False)),
                ('redeemed', models.BooleanField(default=False)),
                ('redeemed_on', models.DateTimeField(blank=True, null=True)),
                ('redeemed_count', models.PositiveIntegerField(blank=True, default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='customer.userinvitation')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_voucher', to='voucher.voucher')),
            ],
            options={
                'verbose_name': 'User Voucher',
                'verbose_name_plural': 'User Vouchers',
                'ordering': ['-currently_used'],
            },
        ),
    ]
