# Generated by Django 3.2.16 on 2023-01-17 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0013_uservouchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referalvoucher',
            old_name='is_redeemed',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='uservouchers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='referalvoucher',
            name='referee_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_voucher', to='voucher.voucher'),
        ),
        migrations.AddField(
            model_name='uservouchers',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='auth.user'),
            preserve_default=False,
        ),
    ]
