# Generated by Django 3.2.16 on 2023-01-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0014_auto_20230117_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referalvoucher',
            name='redeemed_date',
        ),
        migrations.AlterField(
            model_name='uservouchers',
            name='type',
            field=models.CharField(choices=[('referral', 'Referral'), ('firstorder', 'First Order')], default='referral', max_length=255),
        ),
    ]
