# Generated by Django 3.2.16 on 2023-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20221214_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_first_order',
            field=models.BooleanField(default=False),
        ),
    ]
