# Generated by Django 3.2.16 on 2023-01-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_invitation_userinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referrals', to='customer.userinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_referrals', to='customer.userinvitation')),
            ],
            options={
                'verbose_name': 'Referrals',
                'verbose_name_plural': 'Referrals',
                'unique_together': {('user', 'referred_by')},
            },
        ),
    ]
