# Generated by Django 3.2.16 on 2023-01-17 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0010_referrals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='sender_id',
            new_name='sender_invite_model',
        ),
        migrations.RemoveField(
            model_name='userinvitation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referred_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
