# Generated by Django 3.2.16 on 2023-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20221214_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='reference',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reference'),
        ),
    ]
