# Generated by Django 3.2.16 on 2023-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_source_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='reference',
            field=models.TextField(blank=True, verbose_name='Reference'),
        ),
    ]
