# Generated by Django 3.2.16 on 2023-01-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUsModel',
            new_name='FaqModel',
        ),
    ]
