# Generated by Django 3.2.16 on 2023-01-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_rename_aboutusmodel_faqmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='title',
            field=models.TextField(max_length=500),
        ),
    ]
